/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-sqlite'
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from '@payloadcms/db-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-sqlite/drizzle'

export const users_sessions = sqliteTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = sqliteTable(
  'users',
  {
    id: integer('id').primaryKey(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text('email').notNull(),
    resetPasswordToken: text('reset_password_token'),
    resetPasswordExpiration: text('reset_password_expiration').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text('salt'),
    hash: text('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const customers_sessions = sqliteTable(
  'customers_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('customers_sessions_order_idx').on(columns._order),
    index('customers_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [customers.id],
      name: 'customers_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const customers = sqliteTable(
  'customers',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text('email').notNull(),
    resetPasswordToken: text('reset_password_token'),
    resetPasswordExpiration: text('reset_password_expiration').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text('salt'),
    hash: text('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('customers_updated_at_idx').on(columns.updatedAt),
    index('customers_created_at_idx').on(columns.createdAt),
    uniqueIndex('customers_email_idx').on(columns.email),
  ],
)

export const media = sqliteTable(
  'media',
  {
    id: integer('id').primaryKey(),
    alt: text('alt').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const companies = sqliteTable(
  'companies',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    nif: text('nif'),
    address: text('address'),
    phone: text('phone'),
    email: text('email'),
    iban: text('iban'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    primaryColor: text('primary_color').default('#1a56db'),
    createdBy: integer('created_by_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('companies_logo_idx').on(columns.logo),
    index('companies_created_by_idx').on(columns.createdBy),
    index('companies_updated_at_idx').on(columns.updatedAt),
    index('companies_created_at_idx').on(columns.createdAt),
  ],
)

export const clients = sqliteTable(
  'clients',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    nif: text('nif'),
    address: text('address'),
    phone: text('phone'),
    email: text('email'),
    workAddress: text('work_address'),
    createdBy: integer('created_by_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('clients_created_by_idx').on(columns.createdBy),
    index('clients_updated_at_idx').on(columns.updatedAt),
    index('clients_created_at_idx').on(columns.createdAt),
  ],
)

export const quotes_items = sqliteTable(
  'quotes_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    serviceName: text('service_name'),
    description: text('description'),
    quantity: numeric('quantity', { mode: 'number' }),
    unit: text('unit'),
    unitPrice: numeric('unit_price', { mode: 'number' }),
    vatPercentage: numeric('vat_percentage', { mode: 'number' }),
  },
  (columns) => [
    index('quotes_items_order_idx').on(columns._order),
    index('quotes_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [quotes.id],
      name: 'quotes_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const quotes_history = sqliteTable(
  'quotes_history',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    status: text('status'),
    date: text('date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    note: text('note'),
  },
  (columns) => [
    index('quotes_history_order_idx').on(columns._order),
    index('quotes_history_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [quotes.id],
      name: 'quotes_history_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const quotes = sqliteTable(
  'quotes',
  {
    id: integer('id').primaryKey(),
    number: text('number').notNull(),
    projectTitle: text('project_title'),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    validUntil: text('valid_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    notes: text('notes'),
    company: integer('company_id').references(() => companies.id, {
      onDelete: 'set null',
    }),
    client: integer('client_id').references(() => clients.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    status: text('status', {
      enum: ['rascunho', 'enviado', 'em_analise', 'aceite', 'recusado', 'expirado'],
    }).default('rascunho'),
    templateId: text('template_id'),
    createdBy: integer('created_by_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    uniqueIndex('quotes_number_idx').on(columns.number),
    index('quotes_company_idx').on(columns.company),
    index('quotes_client_idx').on(columns.client),
    index('quotes_created_by_idx').on(columns.createdBy),
  ],
)

export const notes_templates = sqliteTable(
  'notes_templates',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    content: text('content').notNull(),
    category: text('category', {
      enum: ['geral', 'pagamento', 'prazo', 'garantia', 'material', 'outro'],
    }).notNull(),
    createdBy: integer('created_by_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [index('notes_templates_created_by_idx').on(columns.createdBy)],
)

export const service_templates = sqliteTable(
  'service_templates',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    description: text('description'),
    category: text('category', {
      enum: [
        'construcao',
        'eletricidade',
        'canalizacao',
        'pintura',
        'limpeza',
        'consultoria',
        'manutencao',
        'outro',
      ],
    }).notNull(),
    unit: text('unit').notNull(),
    unitPrice: numeric('unit_price', { mode: 'number' }).notNull(),
    vatPercentage: numeric('vat_percentage', { mode: 'number' }).notNull(),
    createdBy: integer('created_by_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [index('service_templates_created_by_idx').on(columns.createdBy)],
)

export const settings = sqliteTable(
  'settings',
  {
    id: integer('id').primaryKey(),
    currency: text('currency').notNull().default('EUR'),
    currencyLocale: text('currency_locale').default('pt-PT'),
    language: text('language').default('pt-PT'),
    defaultVat: numeric('default_vat', { mode: 'number' }).default(23),
    quotePrefix: text('quote_prefix').default('ORC'),
    quoteValidity: numeric('quote_validity', { mode: 'number' }).default(30),
    companyDefaultColor: text('company_default_color').default('#1a56db'),
    defaultTemplate: text('default_template').default('classico'),
    createdBy: integer('created_by_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('settings_created_by_idx').on(columns.createdBy),
    index('settings_updated_at_idx').on(columns.updatedAt),
    index('settings_created_at_idx').on(columns.createdAt),
  ],
)

export const notifications = sqliteTable(
  'notifications',
  {
    id: integer('id').primaryKey(),
    type: text('type', { enum: ['info', 'success', 'warning', 'quote'] }).notNull(),
    title: text('title').notNull(),
    message: text('message'),
    read: integer('read', { mode: 'boolean' }).default(false),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdBy: integer('created_by_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('notifications_created_by_idx').on(columns.createdBy),
    index('notifications_updated_at_idx').on(columns.updatedAt),
  ],
)

export const payload_kv = sqliteTable(
  'payload_kv',
  {
    id: integer('id').primaryKey(),
    key: text('key').notNull(),
    data: text('data', { mode: 'json' }).notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = sqliteTable(
  'payload_locked_documents',
  {
    id: integer('id').primaryKey(),
    globalSlug: text('global_slug'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = sqliteTable(
  'payload_locked_documents_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
    customersID: integer('customers_id'),
    mediaID: integer('media_id'),
    companiesID: integer('companies_id'),
    clientsID: integer('clients_id'),
    quotesID: integer('quotes_id'),
    'notes-templatesID': integer('notes_templates_id'),
    'service-templatesID': integer('service_templates_id'),
    settingsID: integer('settings_id'),
    notificationsID: integer('notifications_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_customers_id_idx').on(columns.customersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_companies_id_idx').on(columns.companiesID),
    index('payload_locked_documents_rels_clients_id_idx').on(columns.clientsID),
    index('payload_locked_documents_rels_quotes_id_idx').on(columns.quotesID),
    index('payload_locked_documents_rels_notes_templates_id_idx').on(columns['notes-templatesID']),
    index('payload_locked_documents_rels_service_templates_id_idx').on(
      columns['service-templatesID'],
    ),
    index('payload_locked_documents_rels_settings_id_idx').on(columns.settingsID),
    index('payload_locked_documents_rels_notifications_id_idx').on(columns.notificationsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['customersID']],
      foreignColumns: [customers.id],
      name: 'payload_locked_documents_rels_customers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['companiesID']],
      foreignColumns: [companies.id],
      name: 'payload_locked_documents_rels_companies_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['clientsID']],
      foreignColumns: [clients.id],
      name: 'payload_locked_documents_rels_clients_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['quotesID']],
      foreignColumns: [quotes.id],
      name: 'payload_locked_documents_rels_quotes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['notes-templatesID']],
      foreignColumns: [notes_templates.id],
      name: 'payload_locked_documents_rels_notes_templates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['service-templatesID']],
      foreignColumns: [service_templates.id],
      name: 'payload_locked_documents_rels_service_templates_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['settingsID']],
      foreignColumns: [settings.id],
      name: 'payload_locked_documents_rels_settings_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['notificationsID']],
      foreignColumns: [notifications.id],
      name: 'payload_locked_documents_rels_notifications_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = sqliteTable(
  'payload_preferences',
  {
    id: integer('id').primaryKey(),
    key: text('key'),
    value: text('value', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = sqliteTable(
  'payload_preferences_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
    customersID: integer('customers_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    index('payload_preferences_rels_customers_id_idx').on(columns.customersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['customersID']],
      foreignColumns: [customers.id],
      name: 'payload_preferences_rels_customers_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = sqliteTable(
  'payload_migrations',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_customers_sessions = relations(customers_sessions, ({ one }) => ({
  _parentID: one(customers, {
    fields: [customers_sessions._parentID],
    references: [customers.id],
    relationName: 'sessions',
  }),
}))
export const relations_customers = relations(customers, ({ many }) => ({
  sessions: many(customers_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_companies = relations(companies, ({ one }) => ({
  logo: one(media, {
    fields: [companies.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  createdBy: one(customers, {
    fields: [companies.createdBy],
    references: [customers.id],
    relationName: 'createdBy',
  }),
}))
export const relations_clients = relations(clients, ({ one }) => ({
  createdBy: one(customers, {
    fields: [clients.createdBy],
    references: [customers.id],
    relationName: 'createdBy',
  }),
}))
export const relations_quotes_items = relations(quotes_items, ({ one }) => ({
  _parentID: one(quotes, {
    fields: [quotes_items._parentID],
    references: [quotes.id],
    relationName: 'items',
  }),
}))
export const relations_quotes_history = relations(quotes_history, ({ one }) => ({
  _parentID: one(quotes, {
    fields: [quotes_history._parentID],
    references: [quotes.id],
    relationName: 'history',
  }),
}))
export const relations_quotes = relations(quotes, ({ one, many }) => ({
  company: one(companies, {
    fields: [quotes.company],
    references: [companies.id],
    relationName: 'company',
  }),
  client: one(clients, {
    fields: [quotes.client],
    references: [clients.id],
    relationName: 'client',
  }),
  items: many(quotes_items, {
    relationName: 'items',
  }),
  history: many(quotes_history, {
    relationName: 'history',
  }),
  createdBy: one(customers, {
    fields: [quotes.createdBy],
    references: [customers.id],
    relationName: 'createdBy',
  }),
}))
export const relations_notes_templates = relations(notes_templates, ({ one }) => ({
  createdBy: one(customers, {
    fields: [notes_templates.createdBy],
    references: [customers.id],
    relationName: 'createdBy',
  }),
}))
export const relations_service_templates = relations(service_templates, ({ one }) => ({
  createdBy: one(customers, {
    fields: [service_templates.createdBy],
    references: [customers.id],
    relationName: 'createdBy',
  }),
}))
export const relations_settings = relations(settings, ({ one }) => ({
  createdBy: one(customers, {
    fields: [settings.createdBy],
    references: [customers.id],
    relationName: 'createdBy',
  }),
}))
export const relations_notifications = relations(notifications, ({ one }) => ({
  createdBy: one(customers, {
    fields: [notifications.createdBy],
    references: [customers.id],
    relationName: 'createdBy',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    customersID: one(customers, {
      fields: [payload_locked_documents_rels.customersID],
      references: [customers.id],
      relationName: 'customers',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    companiesID: one(companies, {
      fields: [payload_locked_documents_rels.companiesID],
      references: [companies.id],
      relationName: 'companies',
    }),
    clientsID: one(clients, {
      fields: [payload_locked_documents_rels.clientsID],
      references: [clients.id],
      relationName: 'clients',
    }),
    quotesID: one(quotes, {
      fields: [payload_locked_documents_rels.quotesID],
      references: [quotes.id],
      relationName: 'quotes',
    }),
    'notes-templatesID': one(notes_templates, {
      fields: [payload_locked_documents_rels['notes-templatesID']],
      references: [notes_templates.id],
      relationName: 'notes-templates',
    }),
    'service-templatesID': one(service_templates, {
      fields: [payload_locked_documents_rels['service-templatesID']],
      references: [service_templates.id],
      relationName: 'service-templates',
    }),
    settingsID: one(settings, {
      fields: [payload_locked_documents_rels.settingsID],
      references: [settings.id],
      relationName: 'settings',
    }),
    notificationsID: one(notifications, {
      fields: [payload_locked_documents_rels.notificationsID],
      references: [notifications.id],
      relationName: 'notifications',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    customersID: one(customers, {
      fields: [payload_preferences_rels.customersID],
      references: [customers.id],
      relationName: 'customers',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  customers_sessions: typeof customers_sessions
  customers: typeof customers
  media: typeof media
  companies: typeof companies
  clients: typeof clients
  quotes_items: typeof quotes_items
  quotes_history: typeof quotes_history
  quotes: typeof quotes
  notes_templates: typeof notes_templates
  service_templates: typeof service_templates
  settings: typeof settings
  notifications: typeof notifications
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_customers_sessions: typeof relations_customers_sessions
  relations_customers: typeof relations_customers
  relations_media: typeof relations_media
  relations_companies: typeof relations_companies
  relations_clients: typeof relations_clients
  relations_quotes_items: typeof relations_quotes_items
  relations_quotes_history: typeof relations_quotes_history
  relations_quotes: typeof relations_quotes
  relations_notes_templates: typeof relations_notes_templates
  relations_service_templates: typeof relations_service_templates
  relations_settings: typeof relations_settings
  relations_notifications: typeof relations_notifications
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
